---
# Playbook:     ansible-roles.yml
# Description:  Install ansible roles
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.


# Note: Run from some computers with ansible installed.

- name: ansible-roles.yml
  hosts: [ localhost, controllers ]
  become: yes
  gather_facts: yes

  vars:
    
    re_mode: 'both'        # Valid modes: both, remote and local

  tasks:

  - name: Install ansible package
    package:
      name:  '{{ item }}'
      state: latest
    with_items:
      - ansible
      - git

  - name: Setup {{ re_mode }} ansible onfiguration files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
      owner: root
      group: root
      backup: yes
    when: re_mode == 'remote' or re_mode == 'awx' or re_mode == 'both'
    with_items:
      - { src: files/ansible.src, dest: /etc/ansible/ansible.cfg }
      - { src: requirements.yml, dest: /etc/ansible/requirements.yml }

  - name: Install ansible roles im remote ansible controller
    command: ansible-galaxy install -r /etc/ansible/requirements.yml
    when: re_mode == 'remote' 

  - name: Install ansible roles in local awx controller
    command: ansible-galaxy install -r /etc/ansible/requirements.yml
    when: re_mode == 'awx'
    delegate_to: localhost

  - name: Install ansible roles in local ansible controller
    command: ansible-galaxy install --roles-path roles -r requirements.yml
    when: re_mode == 'local' or re_mode == 'both'
    delegate_to: localhost
    become: no


