---
# Playbook:     debian-python.yml
# Description:  Install python and pre-requisites
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.

# Note: Run from some computers with ansible installed
#       Only run in Debian distribution
 
- name: debian-python.yml
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  
  - name: Install python2
    raw: apt -y update && apt -y upgrade && apt install -y python python-pip python-apt

  - name: Install python3
    raw: apt -y update && apt -y upgrade && apt install -y python3 python3-pip python3-apt