---
# Playbook:     debian-python.yml
# Description:  Install python and pre-requisites
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.

# Note: Run from some computers with ansible installed
#       Only run in Debian distribution
 
- name: debian-python.yml
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  
  - name: Check for Python
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python

  - name: Install python3
    raw: apt -y update && apt -y upgrade && apt install -y python python-pip
    when: check_python.rc != 0

  - name: Check for Python v3
    raw: test -e /usr/bin/python3
    changed_when: false
    failed_when: false
    register: check_python

  - name: Install python
    raw: apt -y update && apt -y upgrade && apt install -y python3 python3-pip
    when: check_python.rc != 0