---
# Playbook:     gitlab-install.yml
# Description:  Install/Update Gitlabs Servers
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.

- name: gitlab-install.yml
  hosts: [gitlabs]
  become: true
  gather_facts: yes

  vars:

    gitlab_external_url: "https://gitlab.example.com/"

  vars_files:

    - vars/sysop-settings.yml

  roles:

    - { role: geerlingguy.gitlab }
