# from galaxy
- src: geerlingguy.pip
- src: geerlingguy.ansible
- src: geerlingguy.awx
- src: geerlingguy.certbot
- src: geerlingguy.docker
- src: geerlingguy.gitlab
- src: geerlingguy.packer
- src: oefenweb.locales

- src: robertdebock.bootstrap
- src: robertdebock.epel
- src: robertdebock.buildtools
- src: robertdebock.python_pip
- src: robertdebock.docker
- src: robertdebock.docker_ce
- src: robertdebock.scl