---
# Playbook:     sysop-setup.yml
# Description:  
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.

# Note: Run from some computers with ansible installed
 
- name: sysop-setup.yml
  hosts: all
  gather_facts: no

  vars:

    local_user: "{{ lookup('env','USER') }}"
    sysop_connected: no

  pre_tasks:

  - name: Get SSH Password if not defined
    pause:
      prompt: "Provide ssh password:"
    when: ansible_password is not defined
    register: ssh_password
    
  tasks:

  - include_vars: vars/sysop-settings.yml
  - include_vars: vars/base-packages.yml

  - name: Setup Password
    set_fact:
      ansible_ssh_pass: '{{ ssh_password.user_input }}'
    when: ssh_password is defined

  - name: Test servers connection
    action: ping
    ignore_unreachable: true
    ignore_errors: true
    register: pingtest

  - name: Set sysop configuration only for servers ready to connection
    block:

      - name: Check if user is connected how sysop user
        set_fact:
          sysop_connected: true
        when: ansible_ssh_user == sysop_userid

      - name: Debug
        debug: var=ansible_ssh_pass
#    when: pingtest.failed | d(pingtest.unreachable) | d(false)





