---
# Playbook:     terraform-install.yml
# Description:  Install/Update terraform infraestructure tool
# Author:       Mauro Rosero P,
# Email:        mrosero@libretechnology.com (mauro.rosero@gmail.com)
# Organization: LIBRETECH, S. A.

- name: terraform-install.yml
  hosts: [terraforms]
  gather_facts: true

  vars:
    linux_os: ['RedHat', 'Debian', 'Suse', 'Ubuntu', 'Slackware', 'Gentoo', 'Archlinux', 'Mandrake', 'Alpine']
    terraform_prefix: /tmp/terraform
    terraform_bin: /tmp
    debugging: false

  vars_files:

    - vars/sysop-settings.yml

  tasks:

    - debug: msg='{{ ansible_distribution }} and {{ ansible_os_family }} and {{ ansible_architecture }}'
      when: debugging == true

    - name: Checck if {{ sysop_group }} exist
      getent:
        database: group
        key: '{{ sysop_group }}'
        fail_key: no

    - name: Check if Linux OS 
      set_fact:
        os_system: 'Linux'
      when: ansible_os_family in linux_os

    - name: Install terraform infraestructure tools for Linux 64bits
      block:

        - name: Download terraform_0.12.9_linux_amd64.zip
          get_url:
            url: https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
            dest: '{{ terraform_prefix }}_{{ os_system }}_{{ ansible_architecture }}.zip'

        - name: Unpack and Install Terraform for {{ ansible_os_family }} {{ ansible_architecture }}) 
          unarchive:
            copy: no
            creates: '{{ terraform_bin }}/terraform'
            src: '{{ terraform_prefix }}_{{ os_system }}_{{ ansible_architecture }}.zip'
            dest: '{{ terraform_bin }}/'
            owner: root
            group: "{{ (getent_group.devops is defined) | ternary('devops', 'root') }}"
            mode: 0550

      when: os_system == 'Linux' and ansible_architecture == 'x86_64'